[build]
 functions = "functions"
 publish = "dist"
 command = "yarn build"

[dev]
port = 1234
command = "yarn start"
publish = "src"

[[redirects]]
  from = "/login1"
  to = "/login"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}